//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IExperimentDefinition
{
	id: string;
	variables: IVariableDefinition[];
	variants: IVariantDefinition[];
	trackedConversions: ITrackedConversion[];
	baselineVariantId: string;
	isActive: boolean;
}
export interface IVariableDefinition
{
	name: string;
	type: VariableType;
}
export interface IVariantDefinition
{
	id: string;
	audience: IAudienceDefinition;
	variables: IVariableInstance[];
}
export interface IConversionType
{
	type: string;
}
export interface IAudienceDefinition
{
	percentage: number;
	includeList: string[];
	excludeList: string[];
}
export interface IVariableInstance
{
	name: string;
	value: any;
}
export interface ITrackedConversion
{
	conversionType: IConversionType;
	requiredMetrics: IVariableInstance[];
}
export interface IExperimentVariantInstance
{
	experiment: string;
	variant: string;
	variables: IVariableInstance[];
}
export interface IExperimentImpressionModel
{
	experiment: string;
	variant: string;
	eventDate: any;
	user: string;
	deduplicationKey?: string;
}
export interface IExperimentConversionModel
{
	conversionType: IConversionType;
	user: string;
	eventDate: any;
	deduplicationKey?: string;
	metrics: IVariableInstance[];
}
export enum VariableType {
	Unknown = 0,
	Boolean = 1,
	String = 2,
	Double = 3
}
